### ISSUE TITLE
add docs to mount secret as file

### ISSUE THREAD

**Issue by shahidhk** [hasura/docs#504]
gist:

`$ hasura secret update credvalue.json -f credvalue.json`

Then modify k8s.yaml to mount this secret as a file, instead of evironment variable.
```yaml
...
spec:
  containers:
  - name: app
    image: my-image
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: hasura-secrets
      items:
      - key: credvalue.json
        path: credvalue.json
```

What happens now is that the file will be available inside the microservice as `/etc/foo/credvalue.json`
